{
  "name": "5c4a93f0-cb7c-4f42-8866-4d6d5c8b9c3a",
  "compatibilityLevel": 1601,
  "createdTimestamp": "2020-11-10T13:23:36.77-06:00",
  "lastUpdate": "2024-03-15T18:05:48.856667-05:00",
  "lastSchemaUpdate": "2024-03-13T17:25:31.13-05:00",
  "lastProcessed": "2024-03-14T12:11:35.66-05:00",
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-US",
    "modifiedTime": "2024-03-13T22:02:52.623333",
    "structureModifiedTime": "2024-03-14T22:30:06.05",
    "tables": [
      {
        "name": "Account",
        "lineageTag": "7aac98fd-1529-47b4-87ad-1f20e739fd6c",
        "modifiedTime": "2022-11-28T23:06:36.736667",
        "structureModifiedTime": "2024-03-14T17:11:32.556667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2020-11-10T19:28:21.996667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T17:11:36.196667",
              "refreshedTime": "2024-03-14T17:11:36.196667"
            }
          },
          {
            "name": "Account",
            "dataType": "string",
            "sourceColumn": "Account",
            "lineageTag": "eda0cb8f-c685-46e8-af41-8d8a17d99ae1",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:22.833333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T17:11:36.196667",
              "refreshedTime": "2024-03-14T17:11:36.196667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:28:22.833333"
              }
            ]
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region",
            "lineageTag": "8effed20-3041-4a23-9b2c-4dc16f98b1a3",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:22.833333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T17:11:36.196667",
              "refreshedTime": "2024-03-14T17:11:36.196667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:28:22.833333"
              }
            ]
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "sortByColumn": "Segment Rank",
            "lineageTag": "d326616a-ea29-42bd-8c4d-efeaf1bd6888",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T17:12:13.946667",
            "structureModifiedTime": "2024-03-14T17:12:13.946667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T17:11:36.196667",
              "refreshedTime": "2024-03-14T17:12:14.053333"
            },
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:28:22.833333"
              }
            ]
          },
          {
            "name": "Account ID",
            "dataType": "int64",
            "sourceColumn": "Account ID",
            "formatString": "0",
            "lineageTag": "6dd1686c-88ca-4da1-8eb6-cf968fd1d7dc",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:22.833333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T17:11:36.196667",
              "refreshedTime": "2024-03-14T17:11:36.196667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:28:22.833333"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "87ba8255-3604-4ff4-a707-989781d644c6",
            "dataCategory": "StateOrProvince",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T16:21:21.693333",
            "structureModifiedTime": "2020-11-10T19:28:22.833333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T17:11:36.196667",
              "refreshedTime": "2024-03-14T17:11:36.196667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:28:22.833333"
              }
            ]
          },
          {
            "name": "Segment Rank",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Segment Rank",
            "formatString": "0",
            "lineageTag": "2660840f-be93-4f87-8602-e1a39ca5f049",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T17:12:06.736667",
            "structureModifiedTime": "2024-03-14T17:12:06.736667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T17:11:36.196667",
              "refreshedTime": "2024-03-14T17:11:36.196667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-14T17:11:32.556667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Account-20fc8f34-ec54-4261-8252-a37decc5f94d",
            "mode": "import",
            "queryGroup": "Semantic Model",
            "state": "ready",
            "modifiedTime": "2024-03-14T17:11:35.66",
            "refreshedTime": "2024-03-14T17:11:35.66",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jVxbc9u2Ev4rmTwfzYgAdXtMnNZx4sSJ5biNe/oAS7TFYwpQeLEj//qzACmJwO6S\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Account = _t, Region = _t, Segment = _t, #\"Account ID\" = _t, State = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Account\", type text}, {\"Region\", type text}, {\"Segment\", type text}, {\"Account ID\", Int64.Type}, {\"State\", type text}}),\n  #\"Inserted conditional column\" = Table.AddColumn(#\"Changed Type\", \"Segment Rank\", each if [Segment] = \"Strategic\" then 1 else if [Segment] = \"Large\" then 2 else 3, Int64.Type)\nin\n    #\"Inserted conditional column\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2020-11-10T19:28:22.886667"
          }
        ]
      },
      {
        "name": "DateTableTemplate_14c69260-1f33-480c-8bcb-55fc0d841ef6",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "00c83c7e-4924-479a-848d-d34bcf3d94bc",
        "modifiedTime": "2022-11-28T23:06:36.736667",
        "structureModifiedTime": "2020-11-10T19:28:21.996667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2020-11-10T19:28:21.996667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:28:22.936667",
              "refreshedTime": "2020-11-10T19:28:22.936667"
            }
          },
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "467fa779-0ae8-4a87-b28b-6f7a7c64784b",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:28:22.936667",
              "refreshedTime": "2020-11-10T19:28:22.936667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "316ad96d-e55f-46f6-b1b4-118c7133694b",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "2020-11-10T19:28:22.94",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:28:22.94",
              "refreshedTime": "2020-11-10T19:28:22.94"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              },
              {
                "name": "TemplateId",
                "value": "Year",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "cd13dd3a-d1df-4cad-88be-a896bbd830f9",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "2020-11-10T19:28:22.94",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:28:22.94",
              "refreshedTime": "2020-11-10T19:28:22.94"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "95fa6f56-1fae-4aa9-818e-42a7c8c3c19c",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "2020-11-10T19:28:22.94",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:28:22.94",
              "refreshedTime": "2020-11-10T19:28:22.94"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              },
              {
                "name": "TemplateId",
                "value": "Month",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "ed22674c-e061-4b1d-b3cb-5b1e6f9be5f2",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "2020-11-10T19:28:22.943333",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:28:22.943333",
              "refreshedTime": "2020-11-10T19:28:22.943333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "ae0d657d-0253-44ad-8fa2-08a9fe346f6d",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "2020-11-10T19:28:22.946667",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:28:22.946667",
              "refreshedTime": "2020-11-10T19:28:22.946667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              },
              {
                "name": "TemplateId",
                "value": "Quarter",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "b11ff696-c6ec-491a-a3b7-9bcf98952425",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "2020-11-10T19:28:22.94",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:28:22.94",
              "refreshedTime": "2020-11-10T19:28:22.94"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              },
              {
                "name": "TemplateId",
                "value": "Day",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_14c69260-1f33-480c-8bcb-55fc0d841ef6-d22408ae-23d2-4de2-b97c-6c3e443a8464",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2020-11-10T19:28:22.936667",
            "refreshedTime": "2020-11-10T19:28:22.936667",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "6cb87e7a-a30a-49d0-a187-d33d1c8ed705",
            "state": "ready",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:28:21.996667",
            "refreshedTime": "2020-11-10T19:28:22.946667",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "d57ae062-a099-4d45-8b0c-c267e6575fd0",
                "modifiedTime": "2022-11-28T23:06:36.736667"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "2470c65c-43e5-4683-839e-c07f5f82902e",
                "modifiedTime": "2022-11-28T23:06:36.736667"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "7e87f89d-935a-42d7-9e29-89eb2c8996a6",
                "modifiedTime": "2022-11-28T23:06:36.736667"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "3a6e83f9-5aff-4a10-adec-5e2fef98bfc7",
                "modifiedTime": "2022-11-28T23:06:36.736667"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy",
                "modifiedTime": "2020-11-10T19:28:21.996667"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true",
            "modifiedTime": "2020-11-10T19:28:21.996667"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy",
            "modifiedTime": "2020-11-10T19:28:21.996667"
          }
        ]
      },
      {
        "name": "Opportunity",
        "lineageTag": "993ca894-f4cd-4277-8aa9-2ae71ffa81a8",
        "modifiedTime": "2022-11-28T23:06:36.736667",
        "structureModifiedTime": "2020-11-10T22:19:38.313333",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2020-11-10T19:31:35.05",
            "structureModifiedTime": "2020-11-10T19:31:35.05",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:35.183333",
              "refreshedTime": "2020-11-10T19:31:35.183333"
            }
          },
          {
            "name": "Opportunity",
            "dataType": "string",
            "sourceColumn": "Opportunity",
            "lineageTag": "f3970741-48cb-448c-be3b-771bcc23a1be",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T22:10:57.493333",
            "structureModifiedTime": "2020-11-10T19:31:35.05",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:35.183333",
              "refreshedTime": "2020-11-10T19:31:35.183333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:31:35.05"
              }
            ]
          },
          {
            "name": "Opportunity ID",
            "dataType": "int64",
            "sourceColumn": "Opportunity ID",
            "formatString": "0",
            "lineageTag": "ccac5bd2-ad2b-4609-b59a-b934c1a4f9cb",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:31:35.05",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:35.183333",
              "refreshedTime": "2020-11-10T19:31:35.183333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:31:35.05"
              }
            ]
          },
          {
            "name": "Rank",
            "dataType": "int64",
            "sourceColumn": "Rank",
            "formatString": "0",
            "lineageTag": "376e3e3a-bb44-4e2a-bb7e-c91bdfe6d356",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:31:35.05",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:35.183333",
              "refreshedTime": "2020-11-10T19:31:35.183333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:31:35.05"
              }
            ]
          },
          {
            "name": "SizeID",
            "dataType": "int64",
            "sourceColumn": "SizeID",
            "formatString": "0",
            "lineageTag": "11c0e110-a5e9-4a26-b530-f62fceb8a543",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:31:35.05",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:35.183333",
              "refreshedTime": "2020-11-10T19:31:35.183333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:31:35.05"
              }
            ]
          },
          {
            "name": "Opportunity Size",
            "dataType": "string",
            "sourceColumn": "Opportunity Size",
            "lineageTag": "a38e20cf-f564-4c7d-a8f7-15cd1aefd2c2",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:31:35.05",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:35.183333",
              "refreshedTime": "2020-11-10T19:31:35.183333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:31:35.05"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Opportunity-589471fd-7f73-4174-b153-69661c96e857",
            "mode": "import",
            "queryGroup": "Semantic Model",
            "state": "ready",
            "modifiedTime": "2024-03-14T17:11:32.746667",
            "refreshedTime": "2020-11-10T19:31:35.18",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jZzLjiW3EUR/xRhvtSg+6vUPFrTQUtBCgAVDgGQLgrTw37srTnbfhmzweNGBAYrD\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t, #\"Opportunity ID\" = _t, Rank = _t, SizeID = _t, #\"Opportunity Size\" = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Name\", type text}, {\"Opportunity ID\", Int64.Type}, {\"Rank\", Int64.Type}, {\"SizeID\", Int64.Type}, {\"Opportunity Size\", type text}}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Name\", \"Opportunity\"}})\nin\n    #\"Renamed Columns\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2020-11-10T19:31:35.1"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      },
      {
        "name": "Partner",
        "lineageTag": "589bfd73-e114-4a1c-81e8-0fe686d0e188",
        "modifiedTime": "2022-11-28T23:06:36.736667",
        "structureModifiedTime": "2020-11-10T22:19:10.996667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2020-11-10T19:31:57.043333",
            "structureModifiedTime": "2020-11-10T19:31:57.043333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:57.163333",
              "refreshedTime": "2020-11-10T19:31:57.163333"
            }
          },
          {
            "name": "Partner",
            "dataType": "string",
            "sourceColumn": "Partner",
            "lineageTag": "a82cdf5b-e209-477f-b5ac-aeca7e8c434a",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:31:57.043333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:57.163333",
              "refreshedTime": "2020-11-10T19:31:57.163333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:31:57.043333"
              }
            ]
          },
          {
            "name": "Partner ID",
            "dataType": "int64",
            "sourceColumn": "Partner ID",
            "formatString": "0",
            "lineageTag": "3455101a-6f1f-4480-bacb-f0e2ae40dbc2",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:31:57.043333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:57.163333",
              "refreshedTime": "2020-11-10T19:31:57.163333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:31:57.043333"
              }
            ]
          },
          {
            "name": "Partner Driven",
            "dataType": "string",
            "sourceColumn": "Partner Driven",
            "lineageTag": "29ec311d-6016-4804-8459-f0e65a28d165",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:31:57.043333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:31:57.163333",
              "refreshedTime": "2020-11-10T19:31:57.163333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:31:57.043333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partner-eaf67aaa-5792-4f9d-a14a-528eec627878",
            "mode": "import",
            "queryGroup": "Semantic Model",
            "state": "ready",
            "modifiedTime": "2024-03-14T17:11:32.746667",
            "refreshedTime": "2020-11-10T19:31:57.16",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"XZbdUtswEIXfJdf1DEkc/1y2zYRSCrSFMgWGi42tJAJbch2Zhjx9d6U4Pc4FzHAU\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Partner = _t, #\"Partner ID\" = _t, #\"Partner Driven\" = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Partner\", type text}, {\"Partner ID\", Int64.Type}, {\"Partner Driven\", type text}}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Partner\", \"Partner\"}})\nin\n    #\"Renamed Columns\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2020-11-10T19:31:57.086667"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      },
      {
        "name": "Product",
        "lineageTag": "b18f3965-1021-4344-b308-488d3992b39a",
        "modifiedTime": "2022-11-28T23:06:36.736667",
        "structureModifiedTime": "2020-11-10T19:32:18.176667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2020-11-10T19:32:18.176667",
            "structureModifiedTime": "2020-11-10T19:32:18.176667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:32:18.31",
              "refreshedTime": "2020-11-10T19:32:18.31"
            }
          },
          {
            "name": "Product",
            "dataType": "string",
            "sourceColumn": "Product",
            "lineageTag": "b48032ae-5548-436d-ada3-82c4033779d5",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T22:10:57.596667",
            "structureModifiedTime": "2020-11-10T19:32:18.176667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:32:18.31",
              "refreshedTime": "2020-11-10T19:32:18.31"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:32:18.176667"
              }
            ]
          },
          {
            "name": "Product ID",
            "dataType": "int64",
            "sourceColumn": "Product ID",
            "formatString": "0",
            "lineageTag": "04649fa4-7e7a-419c-b6bb-726336829b0f",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:32:18.176667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:32:18.31",
              "refreshedTime": "2020-11-10T19:32:18.31"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:32:18.176667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Product-f3a6479b-157b-4f55-8019-ed88961e6c5f",
            "mode": "import",
            "queryGroup": "Semantic Model",
            "state": "ready",
            "modifiedTime": "2024-03-14T17:11:32.746667",
            "refreshedTime": "2020-11-10T19:32:18.306667",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"NdBJD8IgEIbh/8LZg+B+dF/ivl2aHqYNaUgKai3Gny/MV49PmQlvSRIxzjJ6i5aQIm0lYkJv422gYk7JPslRcIc907mxPo532fPSFI+gHmtBNe/2WcsqMI4OmCvKDDxkrwtnokasjf9oWLb5w5ZyzxdLhO2owDHC9saC6DpY45jIOtL/bomykydXm2i0nXX+KGO4RNyFahbSrlRiGW03m1WxRKHsrqs4q9A1fnk+Q9ZEl1hVneb9KqtddLf5i2/zfiqEpT8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Product Code\" = _t, #\"Product ID\" = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Product Code\", type text}, {\"Product ID\", Int64.Type}}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Product Code\", \"Product\"}})\nin\n    #\"Renamed Columns\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2020-11-10T19:32:18.23"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      },
      {
        "name": "Sales Stage",
        "lineageTag": "f0731966-37fb-43dc-aed1-cd8ae74e5e4a",
        "modifiedTime": "2024-03-13T22:10:57.293333",
        "structureModifiedTime": "2020-11-10T19:32:39.816667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2020-11-10T19:32:39.816667",
            "structureModifiedTime": "2020-11-10T19:32:39.816667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:32:39.963333",
              "refreshedTime": "2020-11-10T19:32:39.963333"
            }
          },
          {
            "name": "Probability",
            "dataType": "double",
            "sourceColumn": "Probability",
            "lineageTag": "c83186f8-2cfd-4d84-b76a-79491137185b",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:32:39.816667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:32:39.963333",
              "refreshedTime": "2020-11-10T19:32:39.963333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:32:39.816667"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2022-11-28T23:06:36.733333"
              }
            ]
          },
          {
            "name": "Sales Stage",
            "dataType": "string",
            "sourceColumn": "Sales Stage",
            "lineageTag": "d15e883e-932d-4d99-95ff-c1b9788332f2",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:32:39.816667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:32:39.963333",
              "refreshedTime": "2020-11-10T19:32:39.963333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:32:39.816667"
              }
            ]
          },
          {
            "name": "Sales Stage ID",
            "dataType": "int64",
            "sourceColumn": "Sales Stage ID",
            "formatString": "0",
            "lineageTag": "dfbe4efa-f189-471a-934f-f4010bfdd8a2",
            "summarizeBy": "none",
            "modifiedTime": "2022-11-28T23:06:36.736667",
            "structureModifiedTime": "2020-11-10T19:32:39.816667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2020-11-10T19:32:39.963333",
              "refreshedTime": "2020-11-10T19:32:39.963333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:32:39.816667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Sales Stage-78040bf8-5620-4cd9-9f27-63ac800012a9",
            "mode": "import",
            "queryGroup": "Semantic Model",
            "state": "ready",
            "modifiedTime": "2024-03-14T17:11:32.746667",
            "refreshedTime": "2020-11-10T19:32:39.963333",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMjRQVdJR8klNTAFShkqxOtFKRmChwNLEnMy0SiDLCCxqAhYNzs8pLcnMzwMyjcHCZmDhgKL8gvzixBwg0wQsbAEWdsvMAxpSlQpkmirFxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Probability = _t, #\"Sales Stage\" = _t, #\"Sales Stage ID\" = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Probability\", Percentage.Type}, {\"Sales Stage\", type text}, {\"Sales Stage ID\", Int64.Type}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2020-11-10T19:32:39.883333"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      },
      {
        "name": "Fact",
        "lineageTag": "f92a72fd-3168-4ba3-be9d-5fe62ca23d1e",
        "modifiedTime": "2022-11-28T23:06:36.736667",
        "structureModifiedTime": "2024-03-13T21:43:34.273333",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2020-11-10T19:34:06.8",
            "structureModifiedTime": "2020-11-10T19:34:06.8",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.276667",
              "refreshedTime": "2024-03-13T21:01:38.276667"
            }
          },
          {
            "name": "Opportunity ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Opportunity ID",
            "formatString": "0",
            "lineageTag": "d4d8cefe-c96c-4b7e-9232-a8fb1712760e",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:52:38.28",
            "structureModifiedTime": "2024-03-13T21:52:38.28",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.276667",
              "refreshedTime": "2024-03-13T21:01:38.276667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:34:06.8"
              }
            ]
          },
          {
            "name": "Sales Stage ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sales Stage ID",
            "formatString": "0",
            "lineageTag": "fad21172-70dc-41bb-b1f0-c45c3a8fab68",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:52:46.043333",
            "structureModifiedTime": "2024-03-13T21:52:46.043333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.276667",
              "refreshedTime": "2024-03-13T21:01:38.276667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:34:06.8"
              }
            ]
          },
          {
            "name": "Account ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Account ID",
            "formatString": "0",
            "lineageTag": "dc4de788-ce81-4bb6-80a3-3076bcbd7243",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:52:29.23",
            "structureModifiedTime": "2024-03-13T21:52:29.23",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.276667",
              "refreshedTime": "2024-03-13T21:01:38.276667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:34:06.8"
              }
            ]
          },
          {
            "name": "Partner ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Partner ID",
            "formatString": "0",
            "lineageTag": "5de6cdf7-58d9-4712-88c1-98510defd8f1",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:52:40.75",
            "structureModifiedTime": "2024-03-13T21:52:40.75",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.276667",
              "refreshedTime": "2024-03-13T21:01:38.276667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:34:06.8"
              }
            ]
          },
          {
            "name": "Product ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product ID",
            "formatString": "0",
            "lineageTag": "505dabb5-867e-423e-ac0f-aefdbd889ead",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:52:43.243333",
            "structureModifiedTime": "2024-03-13T21:52:43.243333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.276667",
              "refreshedTime": "2024-03-13T21:01:38.276667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:34:06.8"
              }
            ]
          },
          {
            "name": "Create Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Create Date",
            "formatString": "Long Date",
            "lineageTag": "62167b85-36b8-40ed-97e1-f563d75cde33",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:53:11.353333",
            "structureModifiedTime": "2024-03-13T21:53:11.353333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.276667",
              "refreshedTime": "2024-03-13T21:01:38.276667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2020-11-10T19:34:06.8"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date",
                "modifiedTime": "2024-03-13T20:57:24.706667"
              }
            ]
          },
          {
            "name": "Estimated Close Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Estimated Close Date",
            "formatString": "Long Date",
            "lineageTag": "4974ba0e-5faa-4797-9583-c2ef3fcf7bae",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:53:14.49",
            "structureModifiedTime": "2024-03-13T21:53:14.49",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.276667",
              "refreshedTime": "2024-03-13T21:01:38.276667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T21:01:37.703333"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date",
                "modifiedTime": "2024-03-13T21:01:37.703333"
              }
            ]
          },
          {
            "name": "Expected Revenue",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Expected Revenue",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "63f33b67-c216-46f2-91c4-840e98c9af28",
            "summarizeBy": "sum",
            "modifiedTime": "2024-03-13T21:52:15.623333",
            "structureModifiedTime": "2024-03-13T21:52:15.623333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.293333",
              "refreshedTime": "2024-03-13T21:01:38.293333"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T21:01:37.79"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}",
                "modifiedTime": "2024-03-13T21:01:37.79"
              }
            ]
          },
          {
            "name": "Opportunity Age",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Opportunity Age",
            "formatString": "0",
            "lineageTag": "a2324d25-1f99-498c-8146-9e086a4c7577",
            "summarizeBy": "sum",
            "modifiedTime": "2024-03-13T21:52:18.916667",
            "structureModifiedTime": "2024-03-13T21:52:18.916667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:01:38.276667",
              "refreshedTime": "2024-03-13T21:01:38.276667"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T21:01:37.816667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Fact-1d7ae771-a557-467f-9a2c-7f700b17c050",
            "mode": "import",
            "queryGroup": "Semantic Model",
            "state": "ready",
            "modifiedTime": "2024-03-14T17:11:32.746667",
            "refreshedTime": "2024-03-13T21:01:38.173333",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.Combine({#\"Fact A\", #\"Fact B\"})\nin\n    Source"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2020-11-10T19:34:06.883333"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      },
      {
        "name": "Calendar",
        "lineageTag": "6908774c-3a03-4a60-9129-909c532df427",
        "dataCategory": "Time",
        "modifiedTime": "2024-03-13T20:58:24.443333",
        "structureModifiedTime": "2024-03-14T04:01:25.906667",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isNullable": false,
            "modifiedTime": "2024-03-13T20:58:24.443333",
            "structureModifiedTime": "2024-03-13T20:57:24.456667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:37:39.393333",
              "refreshedTime": "2024-03-14T00:37:39.393333"
            }
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "Short Date",
            "lineageTag": "37356184-d933-46c8-8209-b8471f6b140d",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T22:22:30.823333",
            "structureModifiedTime": "2024-03-13T20:58:24.443333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:37:39.393333",
              "refreshedTime": "2024-03-14T00:37:39.393333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T20:57:24.456667"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date",
                "modifiedTime": "2024-03-13T20:57:24.456667"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "4a4578eb-3a90-4c98-927d-4182606c0171",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:02:37.186667",
            "structureModifiedTime": "2024-03-13T20:57:24.456667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:37:39.393333",
              "refreshedTime": "2024-03-14T00:37:39.393333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T20:57:24.456667"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter",
            "formatString": "0",
            "lineageTag": "34b198e7-8b06-499d-bf5d-758e1d18ee72",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:02:37.186667",
            "structureModifiedTime": "2024-03-13T20:57:24.456667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:37:39.393333",
              "refreshedTime": "2024-03-14T00:37:39.393333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T20:57:24.456667"
              }
            ]
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "Month Number",
            "formatString": "0",
            "lineageTag": "784641e9-d1a1-4236-8e6c-e1735f6124d6",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:02:37.186667",
            "structureModifiedTime": "2024-03-13T20:57:24.456667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:37:39.393333",
              "refreshedTime": "2024-03-14T00:37:39.393333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T20:57:24.456667"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "Month Number",
            "lineageTag": "e1f2db6a-38c4-47b2-9225-f00878407b25",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T22:22:59.106667",
            "structureModifiedTime": "2024-03-13T22:22:59.106667",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:37:39.396667",
              "refreshedTime": "2024-03-14T00:37:39.396667"
            },
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T20:57:24.456667"
              }
            ]
          },
          {
            "name": "Year Quarter",
            "dataType": "int64",
            "sourceColumn": "Year Quarter",
            "formatString": "0",
            "lineageTag": "2007f1ae-7f20-4538-8e9f-6787b03037ca",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T00:37:39.1",
            "structureModifiedTime": "2024-03-14T00:37:38.99",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:37:39.393333",
              "refreshedTime": "2024-03-14T00:37:39.393333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-14T00:37:38.99"
              }
            ]
          },
          {
            "name": "Year Month",
            "dataType": "int64",
            "sourceColumn": "Year Month",
            "formatString": "0",
            "lineageTag": "6c9793f8-1616-4308-8df0-dcbe21277cc1",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T00:37:39.1",
            "structureModifiedTime": "2024-03-14T00:37:39.053333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:37:39.393333",
              "refreshedTime": "2024-03-14T00:37:39.393333"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-14T00:37:39.056667"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "queryGroup": "Semantic Model",
            "state": "ready",
            "modifiedTime": "2024-03-14T17:11:32.746667",
            "refreshedTime": "2024-03-14T00:37:39.3",
            "source": {
              "type": "m",
              "expression": "let\n Source = #table({\"Start Date\",\"End Date\"},\n {\n {\n #date(2021,12,30),\n #date(2023,12,29)\n }\n }),\n #\"Added Custom\" = Table.AddColumn(Source, \"Date\", each {Number.From([Start Date])..Number.From([End Date])}),\n #\"Expanded Custom\" = Table.ExpandListColumn(#\"Added Custom\", \"Date\"),\n #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded Custom\",{\"Start Date\", \"End Date\"}),\n #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Date\", type date}}),\n    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Date]), Int64.Type),\n    #\"Added Custom2\" = Table.AddColumn(#\"Added Custom1\", \"Quarter\", each Date.QuarterOfYear([Date]), Int64.Type),\n    #\"Added Custom3\" = Table.AddColumn(#\"Added Custom2\", \"Month Number\", each Date.Month([Date]), Int64.Type),\n    #\"Added Custom4\" = Table.AddColumn(#\"Added Custom3\", \"Month\", each Text.RemoveRange(Date.MonthName([Date]), 3,Text.Length(Date.MonthName([Date]))-3), type text),\n    #\"Inserted Merged Column\" = Table.AddColumn(#\"Added Custom4\", \"Year Quarter\", each Number.From(Text.Combine({Text.From([Year], \"en-US\"), \"0\", Text.From([Quarter], \"en-US\")})), Int64.Type),\n    #\"Added Custom Column\" = Table.AddColumn(#\"Inserted Merged Column\", \"Year Month\", each Number.FromText(Text.Combine({Date.ToText([Date], \"yyyy\"), Date.ToText([Date], \"MM\")})), Int64.Type)\nin\n    #\"Added Custom Column\""
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "7cbc4320-0e1b-4bb2-817b-82472fe2c82e",
            "state": "ready",
            "modifiedTime": "2024-03-14T04:02:02.776667",
            "structureModifiedTime": "2024-03-14T04:01:51.573333",
            "refreshedTime": "2024-03-14T04:02:02.776667",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "f7c7d94a-9b85-46c3-865d-a01d03e85dee",
                "modifiedTime": "2024-03-14T04:01:25.906667"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "113feb9f-c25e-4f6e-9de6-c50382062828",
                "modifiedTime": "2024-03-14T04:01:33.906667"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "643beaf6-2350-47f2-8d2f-652a7cf1e6c3",
                "modifiedTime": "2024-03-14T04:01:44.906667"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date",
                "lineageTag": "3d7f6a94-ea28-40f4-9f01-4967a565602c",
                "modifiedTime": "2024-03-14T04:01:51.573333"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      },
      {
        "name": "DAX Measures",
        "lineageTag": "1eee524d-68c6-46b3-83a4-6c5e90a3535d",
        "modifiedTime": "2024-03-13T21:42:28.06",
        "structureModifiedTime": "2024-03-15T02:35:16.573333",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2024-03-13T21:42:28.06",
            "structureModifiedTime": "2024-03-13T21:42:28.06",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:42:28.23",
              "refreshedTime": "2024-03-13T21:42:28.23"
            }
          },
          {
            "name": "Column1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Column1",
            "lineageTag": "6d2b6691-7452-4c68-bf86-8586e85ef421",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-13T21:42:43.33",
            "structureModifiedTime": "2024-03-13T21:42:43.33",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-13T21:42:28.23",
              "refreshedTime": "2024-03-13T21:42:28.23"
            },
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T21:42:28.06"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DAX Measures",
            "mode": "import",
            "queryGroup": "Semantic Model",
            "state": "ready",
            "modifiedTime": "2024-03-14T17:11:32.746667",
            "refreshedTime": "2024-03-13T21:42:28.18",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})\nin\n    #\"Changed Type\""
            }
          }
        ],
        "measures": [
          {
            "name": "Avg Opportunity Age",
            "expression": "AVERAGE('Fact'[Opportunity Age])",
            "displayFolder": "Opportunity by Close Date",
            "lineageTag": "9bfae785-435c-4e03-88be-8d4d3a8df8df",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T00:57:44.366667",
            "structureModifiedTime": "2024-03-13T21:42:36.873333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-13T21:42:36.873333"
              }
            ]
          },
          {
            "name": "Avg Revenue",
            "expression": "AVERAGE('Fact'[Expected Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Revenue by Close Date",
            "lineageTag": "5ca57a64-b692-4631-bbf4-2b8094913054",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:14:03.573333",
            "structureModifiedTime": "2024-03-13T21:43:18.49",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}",
                "modifiedTime": "2024-03-14T01:14:03.573333"
              }
            ]
          },
          {
            "name": "Opportunity Count",
            "expression": "DISTINCTCOUNT('Fact'[Opportunity ID])",
            "formatString": "0",
            "displayFolder": "Opportunity by Close Date",
            "lineageTag": "d1fc1df6-dcf2-4676-870b-cf30b11e4c7a",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T05:09:27.1",
            "structureModifiedTime": "2024-03-13T21:43:25.763333"
          },
          {
            "name": "Revenue",
            "expression": "SUM('Fact'[Expected Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Revenue by Close Date",
            "lineageTag": "376639e5-fb0e-42f5-a83c-d60247748851",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:14:28.04",
            "structureModifiedTime": "2024-03-13T21:43:29.613333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}",
                "modifiedTime": "2024-03-14T01:14:28.036667"
              }
            ]
          },
          {
            "name": "Max Opportunity Age",
            "expression": "MAX('Fact'[Opportunity Age])",
            "formatString": "0",
            "displayFolder": "Opportunity by Close Date",
            "lineageTag": "a15aaea9-1f9c-48a9-866d-e3bd2a27cbcc",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T00:57:50.256667",
            "structureModifiedTime": "2024-03-13T21:48:06.453333"
          },
          {
            "name": "Min Opportunity Age",
            "expression": "MIN('Fact'[Opportunity Age])",
            "formatString": "0",
            "displayFolder": "Opportunity by Close Date",
            "lineageTag": "c88edaec-41a5-4138-b591-b4a0a5867af3",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T00:57:54.593333",
            "structureModifiedTime": "2024-03-13T21:48:33.3"
          },
          {
            "name": "Max Revenue",
            "expression": "MAX('Fact'[Expected Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Revenue by Close Date",
            "lineageTag": "a7e206b9-b41a-42a5-aaa2-92f7c55f7bea",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:14:12.536667",
            "structureModifiedTime": "2024-03-13T21:50:05.806667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}",
                "modifiedTime": "2024-03-14T01:14:12.536667"
              }
            ]
          },
          {
            "name": "Min Revenue",
            "expression": "MIN('Fact'[Expected Revenue])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Revenue by Close Date",
            "lineageTag": "dd4fd18d-8cf1-4375-a12f-c1ab1382ea41",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:14:19.703333",
            "structureModifiedTime": "2024-03-13T21:50:24.783333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}",
                "modifiedTime": "2024-03-14T01:14:19.703333"
              }
            ]
          },
          {
            "name": "Revenue (Create Date)",
            "expression": "CALCULATE([Revenue], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Revenue by Create Date",
            "lineageTag": "615f3790-eb7f-479d-b31d-c4c4d1cb633f",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:31:34.43",
            "structureModifiedTime": "2024-03-14T00:55:31.003333"
          },
          {
            "name": "Avg Revenue (Create Date)",
            "expression": "CALCULATE([Avg Revenue], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Revenue by Create Date",
            "lineageTag": "591f69f9-184e-45a7-ab47-95cf1e3fb910",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:31:06.206667",
            "structureModifiedTime": "2024-03-14T00:58:13.77"
          },
          {
            "name": "Max Revenue (Create Date)",
            "expression": "CALCULATE([Max Revenue], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Revenue by Create Date",
            "lineageTag": "569b3955-43ae-4e4f-a27f-3051ccd98e64",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:31:14.946667",
            "structureModifiedTime": "2024-03-14T00:59:00.89"
          },
          {
            "name": "Min Revenue (Create Date)",
            "expression": "CALCULATE([Min Revenue], USERELATIONSHIP('Calendar'[Date], 'Fact'[Create Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Revenue by Create Date",
            "lineageTag": "19025926-50cf-42cd-ba3c-281f44c44f97",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:31:25.273333",
            "structureModifiedTime": "2024-03-14T00:59:50.123333"
          },
          {
            "name": "Avg Opportunity Age (Create Date)",
            "expression": "CALCULATE([Avg Opportunity Age], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "displayFolder": "Opportunity by Create Date",
            "lineageTag": "fa29e655-6b02-443a-8a39-b03a96d7c3ce",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:30:21.626667",
            "structureModifiedTime": "2024-03-14T01:10:26.216667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T01:11:03.97"
              }
            ]
          },
          {
            "name": "Max Opportunity Age (Create Date)",
            "expression": "CALCULATE([Max Opportunity Age], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "displayFolder": "Opportunity by Create Date",
            "lineageTag": "355d17e9-f06a-43d1-a6ec-2d63cb72b21e",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:30:31.426667",
            "structureModifiedTime": "2024-03-14T01:11:18.29",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T01:11:49.156667"
              }
            ]
          },
          {
            "name": "Min Opportunity Age (Create Date)",
            "expression": "CALCULATE([Min Opportunity Age], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "displayFolder": "Opportunity by Create Date",
            "lineageTag": "f2462cab-b314-4f63-9e5b-91434cfffc9a",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T01:30:39.66",
            "structureModifiedTime": "2024-03-14T01:11:54.096667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T01:12:24.76"
              }
            ]
          },
          {
            "name": "Opportunity Count (Create Date)",
            "expression": "CALCULATE([Opportunity Count], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "formatString": "#,0",
            "displayFolder": "Opportunity by Create Date",
            "lineageTag": "9d108029-33fc-467e-8608-a225f0a6c964",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T22:31:12.626667",
            "structureModifiedTime": "2024-03-14T01:12:29.99",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}",
                "modifiedTime": "2024-03-14T22:31:12.626667"
              }
            ]
          },
          {
            "name": "Revenue MoM Color",
            "expression": "\nvar _base = [Revenue]\nvar _pm = CALCULATE( [Revenue], DATEADD('Calendar'[Date], -1, MONTH))\nvar _pct = DIVIDE(_base - _pm, _pm)\nreturn\nSWITCH(TRUE(),_pct < -.1, \"#FF0000\", _pct <= .1, \"#F3C911\", _pct > .1, \"#339933\", \"#000000\")",
            "displayFolder": "Formatting",
            "lineageTag": "a47227d8-ab86-43de-baf2-55036ef6b473",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:05:49.056667",
            "structureModifiedTime": "2024-03-14T01:49:13.97",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T01:52:46.613333"
              }
            ]
          },
          {
            "name": "Revenue (Create Date) MoM Color",
            "expression": "CALCULATE([Revenue MoM Color], USERELATIONSHIP('Calendar'[Date], 'Fact'[Create Date]))",
            "displayFolder": "Formatting",
            "lineageTag": "1b6dac56-bf21-4197-a6ce-1e61c8da4924",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:09:10.103333",
            "structureModifiedTime": "2024-03-14T02:00:13.59",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T02:00:45.303333"
              }
            ]
          },
          {
            "name": "Revenue QoQ Color",
            "expression": "\nvar _base = [Revenue]\nvar _pq = CALCULATE( [Revenue], DATEADD('Calendar'[Date], -1, QUARTER))\nvar _pct = DIVIDE(_base - _pq, _pq)\nreturn\nSWITCH(TRUE(),_pct < -.1, \"#FF0000\", _pct <= .1, \"#F3C911\", _pct > .1, \"#339933\", \"#000000\")",
            "displayFolder": "Formatting",
            "lineageTag": "648486b3-d387-4ab3-a17e-abf671069e0f",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:05:35.776667",
            "structureModifiedTime": "2024-03-14T02:03:00.29",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T02:03:19.11"
              }
            ]
          },
          {
            "name": "Revenue (Create Date) QoQ Color",
            "expression": "CALCULATE([Revenue QoQ Color], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "displayFolder": "Formatting",
            "lineageTag": "cd661202-2c74-4a04-8f7f-a7ca0f6f3c19",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:09:16.756667",
            "structureModifiedTime": "2024-03-14T02:03:31.636667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T02:05:14.943333"
              }
            ]
          },
          {
            "name": "Opportunity Count MoM Color",
            "expression": "\nvar _base = [Opportunity Count]\nvar _pm = CALCULATE( [Opportunity Count], DATEADD('Calendar'[Date], -1, MONTH))\nvar _pct = DIVIDE(_base - _pm, _pm)\nreturn\nSWITCH(TRUE(),_pct < -.1, \"#FF0000\", _pct <= .1, \"#F3C911\", _pct > .1, \"#339933\", \"#000000\")",
            "displayFolder": "Formatting",
            "lineageTag": "9d108cb6-cc06-46f6-8bf2-fdbac0fd956b",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:08:38.736667",
            "structureModifiedTime": "2024-03-14T02:06:45.476667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T02:07:18.326667"
              }
            ]
          },
          {
            "name": "Opportunity Count (Create Date) MoM Color",
            "expression": "CALCULATE([Opportunity Count MoM Color], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "displayFolder": "Formatting",
            "lineageTag": "a40432c8-3b12-4b7d-93a1-f876c8aeba1f",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:08:57.59",
            "structureModifiedTime": "2024-03-14T02:07:21.656667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T02:08:09.136667"
              }
            ]
          },
          {
            "name": "Opportunity Count QoQ Color",
            "expression": "\nvar _base = [Opportunity Count]\nvar _pq = CALCULATE( [Opportunity Count], DATEADD('Calendar'[Date], -1, QUARTER))\nvar _pct = DIVIDE(_base - _pq, _pq)\nreturn\nSWITCH(TRUE(),_pct < -.1, \"#FF0000\", _pct <= .1, \"#F3C911\", _pct > .1, \"#339933\", \"#000000\")",
            "displayFolder": "Formatting",
            "lineageTag": "3a16d270-a810-48ee-8138-caa59ba2510b",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:13:04.816667",
            "structureModifiedTime": "2024-03-14T02:11:56.496667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T02:12:12.196667"
              }
            ]
          },
          {
            "name": "Opportunity Count (Create Date) QoQ Color",
            "expression": "CALCULATE([Opportunity Count QoQ Color], USERELATIONSHIP('Calendar'[Date], 'Fact'[Create Date]))",
            "displayFolder": "Formatting",
            "lineageTag": "f3128aad-7f89-4233-85e3-3edef502a105",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:13:00",
            "structureModifiedTime": "2024-03-14T02:12:16.263333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T02:12:54.98"
              }
            ]
          },
          {
            "name": "Revenue MoM %",
            "expression": "\nvar _base = [Revenue]\nvar _pm = CALCULATE( [Revenue], DATEADD('Calendar'[Date], -1, MONTH))\nRETURN DIVIDE(_base - _pm, _pm)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Revenue by Close Date",
            "lineageTag": "bf85dfd3-ff95-47e0-b819-9299906a8e44",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:18:41.896667",
            "structureModifiedTime": "2024-03-14T02:14:37.13"
          },
          {
            "name": "Revenue QoQ %",
            "expression": "\nvar _base = [Revenue]\nvar _pq = CALCULATE( [Revenue], DATEADD('Calendar'[Date], -1, QUARTER))\nRETURN DIVIDE(_base - _pq, _pq)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Revenue by Close Date",
            "lineageTag": "6f818b6e-3d1f-4204-a6e8-00cd283da624",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:19:28.146667",
            "structureModifiedTime": "2024-03-14T02:15:54.376667"
          },
          {
            "name": "Revenue MoM % (Create Date)",
            "expression": "CALCULATE([Revenue MoM %], USERELATIONSHIP('Calendar'[Date], 'Fact'[Create Date]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Revenue by Create Date",
            "lineageTag": "0dc3d5c7-05cb-4451-a59b-41aedd47d199",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:18:41.923333",
            "structureModifiedTime": "2024-03-14T02:17:26.236667"
          },
          {
            "name": "Revenue QoQ % (Create Date)",
            "expression": "CALCULATE([Revenue QoQ %], USERELATIONSHIP('Calendar'[Date], 'Fact'[Create Date]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Revenue by Create Date",
            "lineageTag": "584be082-5172-4c6f-9a6e-3c659eea21b1",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T02:20:23.786667",
            "structureModifiedTime": "2024-03-14T02:19:50.6"
          },
          {
            "name": "Opportunity Count MoM %",
            "expression": "\nvar _base = [Opportunity Count]\nvar _pm = CALCULATE( [Opportunity Count], DATEADD('Calendar'[Date], -1, MONTH))\nRETURN DIVIDE(_base - _pm, _pm)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Opportunity by Close Date",
            "lineageTag": "7962ac4d-3592-486a-a5a5-74ab2a2eb37b",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T03:56:37.353333",
            "structureModifiedTime": "2024-03-14T03:55:16.376667"
          },
          {
            "name": "Opportunity Count QoQ %",
            "expression": "\nvar _base = [Opportunity Count]\nvar _pq = CALCULATE( [Opportunity Count], DATEADD('Calendar'[Date], -1, QUARTER))\nRETURN DIVIDE(_base - _pq, _pq)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Opportunity by Close Date",
            "lineageTag": "0b18f3fd-9082-4cef-827b-b56d12cf5451",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T03:56:41.79",
            "structureModifiedTime": "2024-03-14T03:55:57.356667"
          },
          {
            "name": "Opportunity Count (Create Date) MoM %",
            "expression": "CALCULATE([Opportunity Count MoM %], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Opportunity by Create Date",
            "lineageTag": "58223bdf-a34b-445f-9741-20d4a4906668",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T03:57:56.136667",
            "structureModifiedTime": "2024-03-14T03:56:51.043333"
          },
          {
            "name": "Opportunity Count (Create Date) QoQ %",
            "expression": "CALCULATE([Opportunity Count QoQ %], USERELATIONSHIP('Calendar'[Date],'Fact'[Create Date]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Opportunity by Create Date",
            "lineageTag": "159bce05-1846-478e-b853-2815d1432f27",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T03:58:43.08",
            "structureModifiedTime": "2024-03-14T03:58:07.176667"
          },
          {
            "name": "Max Close Date",
            "expression": "Max('Fact'[Estimated Close Date])",
            "displayFolder": "Dates",
            "lineageTag": "cb6ee382-1cb5-4695-852c-0e0ad6330700",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T04:38:37.296667",
            "structureModifiedTime": "2024-03-14T04:37:06.496667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T04:37:21.543333"
              }
            ]
          },
          {
            "name": "Max Create Date",
            "expression": "Max('Fact'[Create Date])",
            "displayFolder": "Dates",
            "lineageTag": "ea8207a2-2c68-4cbc-b562-59769320bfd3",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T04:38:40.293333",
            "structureModifiedTime": "2024-03-14T04:37:35.896667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T04:37:48.126667"
              }
            ]
          },
          {
            "name": "Min Close Date",
            "expression": "MIN('Fact'[Estimated Close Date])",
            "displayFolder": "Dates",
            "lineageTag": "4fbd2180-f93e-4d33-9bae-dcf106d9971f",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T04:38:43.72",
            "structureModifiedTime": "2024-03-14T04:37:51.333333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T04:38:05.286667"
              }
            ]
          },
          {
            "name": "Min Create Date",
            "expression": "MIN('Fact'[Create Date])",
            "displayFolder": "Dates",
            "lineageTag": "e1f3b742-97ce-4412-909e-d9b9a02d3d22",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T04:38:31.666667",
            "structureModifiedTime": "2024-03-14T04:38:07.913333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-14T04:38:21.096667"
              }
            ]
          },
          {
            "name": "Account Count",
            "expression": "DISTINCTCOUNT('Fact'[Account ID])",
            "formatString": "#,0",
            "displayFolder": "Dimension Count",
            "lineageTag": "d2a14bc9-3944-434b-aad4-cca33377f0a8",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T16:44:50.34",
            "structureModifiedTime": "2024-03-14T16:41:32.91",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}",
                "modifiedTime": "2024-03-14T16:42:34.61"
              }
            ]
          },
          {
            "name": "Partner Count",
            "expression": "DISTINCTCOUNT('Fact'[Partner ID])",
            "formatString": "#,0",
            "displayFolder": "Dimension Count",
            "lineageTag": "ee732370-ae54-4de5-97bb-c2730b0c85e4",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T16:44:41.78",
            "structureModifiedTime": "2024-03-14T16:41:59.06",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}",
                "modifiedTime": "2024-03-14T16:42:25.363333"
              }
            ]
          },
          {
            "name": "Product Count",
            "expression": "DISTINCTCOUNT('Fact'[Product ID])",
            "formatString": "#,0",
            "displayFolder": "Dimension Count",
            "lineageTag": "2e29e19c-8c59-44ee-b435-68d39eaf516f",
            "dataType": "variant",
            "modifiedTime": "2024-03-14T16:44:46.356667",
            "structureModifiedTime": "2024-03-14T16:43:44.486667",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}",
                "modifiedTime": "2024-03-14T16:44:18.443333"
              }
            ]
          },
          {
            "name": "First Account",
            "expression": "FIRSTNONBLANK(Account[Account],TRUE())",
            "displayFolder": "Formatting",
            "lineageTag": "5950b745-5edb-4785-bf36-6459d89e22b7",
            "dataType": "variant",
            "modifiedTime": "2024-03-15T02:34:41.596667",
            "structureModifiedTime": "2024-03-15T02:19:23.703333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-15T02:19:43.653333"
              }
            ]
          },
          {
            "name": "First Partner",
            "expression": "FIRSTNONBLANK(Partner[Partner],TRUE())",
            "displayFolder": "Formatting",
            "lineageTag": "7fe5c1b0-ae6d-4418-948c-66ae3ec5b6f1",
            "dataType": "variant",
            "modifiedTime": "2024-03-15T02:34:45.53",
            "structureModifiedTime": "2024-03-15T02:19:47.273333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-15T02:20:13.456667"
              }
            ]
          },
          {
            "name": "First Stage",
            "expression": "FIRSTNONBLANK('Sales Stage'[Sales Stage],TRUE())",
            "displayFolder": "Formatting",
            "lineageTag": "7c155441-72cd-43dd-b9f1-d836d4339a7d",
            "dataType": "variant",
            "modifiedTime": "2024-03-15T02:34:49.21",
            "structureModifiedTime": "2024-03-15T02:20:19.05",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-15T02:20:36.24"
              }
            ]
          },
          {
            "name": "Create Date",
            "expression": "CALCULATE(MAX('Calendar'[Date]), USERELATIONSHIP('Calendar'[Date], 'Fact'[Create Date]))",
            "displayFolder": "Formatting",
            "lineageTag": "6cffce97-e030-431b-85d7-878701ca7f7d",
            "dataType": "variant",
            "modifiedTime": "2024-03-15T02:34:37.61",
            "structureModifiedTime": "2024-03-15T02:33:56.013333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-15T02:34:27.196667"
              }
            ]
          },
          {
            "name": "Esimated Close Date",
            "expression": "MAX('Calendar'[Date])",
            "lineageTag": "c09ef775-4857-4121-826c-50ece79761ec",
            "dataType": "variant",
            "modifiedTime": "2024-03-15T02:35:36.18",
            "structureModifiedTime": "2024-03-15T02:35:16.573333",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}",
                "modifiedTime": "2024-03-15T02:35:36.18"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2024-03-13T21:42:28.06"
          }
        ]
      },
      {
        "name": "Time Intelligence Modifiers",
        "lineageTag": "894ed122-a57b-4da9-a8c8-6dfad50ba2c1",
        "modifiedTime": "2024-03-13T22:28:47.486667",
        "structureModifiedTime": "2024-03-13T22:02:52.623333",
        "calculationGroup": {
          "modifiedTime": "2024-03-13T22:02:52.623333",
          "calculationItems": [
            {
              "name": "Base Measure",
              "expression": "SELECTEDMEASURE()",
              "ordinal": 0,
              "modifiedTime": "2024-03-14T00:32:11.103333",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()",
                "modifiedTime": "2024-03-14T22:36:34.633333"
              }
            },
            {
              "name": "Prior Month",
              "expression": "CALCULATE( SELECTEDMEASURE(), DATEADD('Calendar'[Date], -1, MONTH))",
              "ordinal": 3,
              "modifiedTime": "2024-03-14T00:53:43.016667",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()",
                "modifiedTime": "2024-03-14T22:36:59.736667"
              }
            },
            {
              "name": "MoM %",
              "expression": "\nvar _base = SELECTEDMEASURE()\nvar _pm = CALCULATE( SELECTEDMEASURE(), DATEADD('Calendar'[Date], -1, MONTH))\nreturn\nDIVIDE(_base - _pm, _pm)",
              "ordinal": 4,
              "modifiedTime": "2024-03-14T00:53:43.016667",
              "formatStringDefinition": {
                "expression": "\"0.0%\"",
                "modifiedTime": "2024-03-13T22:25:56.816667"
              }
            },
            {
              "name": "Prior Quarter",
              "expression": "CALCULATE( SELECTEDMEASURE(), DATEADD('Calendar'[Date], -1, QUARTER))",
              "ordinal": 6,
              "modifiedTime": "2024-03-14T00:53:43.016667",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()",
                "modifiedTime": "2024-03-14T22:37:15.473333"
              }
            },
            {
              "name": "QoQ %",
              "expression": "\nvar _base = SELECTEDMEASURE()\nvar _pq = CALCULATE( SELECTEDMEASURE(), DATEADD('Calendar'[Date], -1, QUARTER))\nreturn\nDIVIDE(_base - _pq, _pq)",
              "ordinal": 7,
              "modifiedTime": "2024-03-14T00:53:43.016667"
            },
            {
              "name": "Cumulative",
              "expression": "\nCALCULATE (\n    SELECTEDMEASURE(),\n    FILTER (\n        ALLSELECTED('Calendar'),\n        'Calendar'[Date] <= MAX ( 'Calendar'[Date] )\n    )\n)\n",
              "ordinal": 1,
              "modifiedTime": "2024-03-14T00:53:43.016667",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()",
                "modifiedTime": "2024-03-14T22:36:44.103333"
              }
            },
            {
              "name": "QTD",
              "expression": "TOTALQTD(SELECTEDMEASURE(),'Calendar'[Date])",
              "ordinal": 5,
              "modifiedTime": "2024-03-14T00:53:43.016667",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()",
                "modifiedTime": "2024-03-14T22:37:07.426667"
              }
            },
            {
              "name": "MTD",
              "expression": "TOTALMTD(SELECTEDMEASURE(),'Calendar'[Date])",
              "ordinal": 2,
              "modifiedTime": "2024-03-14T00:53:43.016667",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()",
                "modifiedTime": "2024-03-14T22:36:52.273333"
              }
            }
          ]
        },
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2024-03-14T00:54:04.4",
            "structureModifiedTime": "2024-03-13T22:02:52.623333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:54:04.4",
              "refreshedTime": "2024-03-14T00:54:04.4"
            }
          },
          {
            "name": "Measure Transformations",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "fbb20696-7983-42ec-82df-f49b76984294",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T00:54:04.4",
            "structureModifiedTime": "2024-03-13T22:02:52.623333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:54:04.4",
              "refreshedTime": "2024-03-14T00:54:04.4"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T22:02:52.623333"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "formatString": "0",
            "lineageTag": "55be3fc3-dd13-4ec5-b8c9-36a2f6e17bd3",
            "summarizeBy": "sum",
            "modifiedTime": "2024-03-14T00:54:04.4",
            "structureModifiedTime": "2024-03-13T22:02:52.623333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T00:54:04.4",
              "refreshedTime": "2024-03-14T00:54:04.4"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T22:02:52.623333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Time Intelligence Modifiers",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2024-03-14T00:54:04.4",
            "refreshedTime": "2024-03-14T00:54:04.4",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Dimension Parameter",
        "lineageTag": "bc554850-15da-479b-a01c-7aaa4e6c611a",
        "modifiedTime": "2024-03-13T22:11:56.32",
        "structureModifiedTime": "2024-03-13T22:11:56.04",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2024-03-14T22:38:55.876667",
            "structureModifiedTime": "2024-03-13T22:11:56.04",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T22:38:55.893333",
              "refreshedTime": "2024-03-15T23:05:48.776667"
            }
          },
          {
            "type": "calculatedTableColumn",
            "name": "Dimension Parameter",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Dimension Parameter Order",
            "lineageTag": "caee8b25-5dc1-4e04-886d-5c6a93219ba1",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T22:38:55.876667",
            "structureModifiedTime": "2024-03-13T22:11:56.32",
            "refreshedTime": "1699-12-31T00:00:00",
            "relatedColumnDetails": {
              "modifiedTime": "2024-03-13T22:11:56.32",
              "groupByColumns": [
                {
                  "groupingColumn": "Dimension Parameter Fields",
                  "modifiedTime": "2024-03-13T22:11:56.32"
                }
              ]
            },
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T22:38:55.893333",
              "refreshedTime": "2024-03-15T23:05:48.776667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T22:11:56.103333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Dimension Parameter Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Dimension Parameter Order",
            "lineageTag": "e93612ec-a048-4a1e-aa2a-1ecb1228faf3",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T22:38:55.876667",
            "structureModifiedTime": "2024-03-13T22:11:56.32",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T22:38:55.893333",
              "refreshedTime": "2024-03-15T23:05:48.776667"
            },
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                },
                "modifiedTime": "2024-03-13T22:11:56.32"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T22:11:56.103333"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Dimension Parameter Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "038e3129-d122-4d4f-a29f-2e008e74c510",
            "summarizeBy": "sum",
            "modifiedTime": "2024-03-14T22:38:55.876667",
            "structureModifiedTime": "2024-03-13T22:11:56.073333",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T22:38:55.893333",
              "refreshedTime": "2024-03-15T23:05:48.776667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-13T22:11:56.103333"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dimension Parameter",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2024-03-14T22:38:55.876667",
            "refreshedTime": "2024-03-15T23:05:48.776667",
            "source": {
              "type": "calculated",
              "expression": "{\n    (\"Account\", NAMEOF('Account'[Account]), 0),\n    (\"Opportunity\", NAMEOF('Opportunity'[Opportunity]), 1),\n    (\"Product\", NAMEOF('Product'[Product]), 2),\n    (\"Partner\", NAMEOF('Partner'[Partner]), 3),\n    (\"Year Month\", NAMEOF('Calendar'[Year Month]), 4),\n    (\"Year Quarter\", NAMEOF('Calendar'[Year Quarter]), 5)\n}"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "618fe48de81e41ea9e296e894ecb5710",
            "modifiedTime": "2024-03-13T22:11:56.103333"
          }
        ]
      },
      {
        "name": "Measure Parameter",
        "lineageTag": "e7ff22b6-5ea9-49c0-9fdc-a17f26e88680",
        "modifiedTime": "2024-03-14T22:30:06.78",
        "structureModifiedTime": "2024-03-14T22:30:06.05",
        "columns": [
          {
            "type": "rowNumber",
            "name": "RowNumber-2662979B-1795-4F74-8F37-6A1BA8059B61",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "isNullable": false,
            "modifiedTime": "2024-03-14T22:30:22.086667",
            "structureModifiedTime": "2024-03-14T22:30:06.05",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T22:30:22.09",
              "refreshedTime": "2024-03-15T23:05:48.776667"
            }
          },
          {
            "type": "calculatedTableColumn",
            "name": "Measure Parameter",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Measure Parameter Order",
            "lineageTag": "06f44ef5-07e8-4542-a53a-aae32dca496c",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T22:30:22.086667",
            "structureModifiedTime": "2024-03-14T22:30:06.78",
            "refreshedTime": "1699-12-31T00:00:00",
            "relatedColumnDetails": {
              "modifiedTime": "2024-03-14T22:30:06.78",
              "groupByColumns": [
                {
                  "groupingColumn": "Measure Parameter Fields",
                  "modifiedTime": "2024-03-14T22:30:06.78"
                }
              ]
            },
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T22:30:22.09",
              "refreshedTime": "2024-03-15T23:05:48.776667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-14T22:30:06.35"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Measure Parameter Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Measure Parameter Order",
            "lineageTag": "1c063e8f-975b-419d-9837-0635552cd372",
            "summarizeBy": "none",
            "modifiedTime": "2024-03-14T22:30:22.086667",
            "structureModifiedTime": "2024-03-14T22:30:06.78",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T22:30:22.09",
              "refreshedTime": "2024-03-15T23:05:48.776667"
            },
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                },
                "modifiedTime": "2024-03-14T22:30:06.78"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-14T22:30:06.35"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Measure Parameter Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "0c11180d-b931-431e-bfe7-9f6d6490e010",
            "summarizeBy": "sum",
            "modifiedTime": "2024-03-14T22:30:22.086667",
            "structureModifiedTime": "2024-03-14T22:30:06.18",
            "refreshedTime": "1699-12-31T00:00:00",
            "attributeHierarchy": {
              "state": "ready",
              "modifiedTime": "2024-03-14T22:30:22.086667",
              "refreshedTime": "2024-03-15T23:05:48.776667"
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic",
                "modifiedTime": "2024-03-14T22:30:06.35"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Measure Parameter",
            "mode": "import",
            "state": "ready",
            "modifiedTime": "2024-03-14T22:30:22.086667",
            "refreshedTime": "2024-03-15T23:05:48.776667",
            "source": {
              "type": "calculated",
              "expression": "{\n    (\"Revenue\", NAMEOF('DAX Measures'[Revenue]), 0),\n    (\"Revenue (Create Date)\", NAMEOF('DAX Measures'[Revenue (Create Date)]), 1),\n    (\"Opportunities\", NAMEOF('DAX Measures'[Opportunity Count]), 2),\n    (\"Opportunities (Create Date)\", NAMEOF('DAX Measures'[Opportunity Count (Create Date)]), 3)\n}"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7903473724f74ca88464b536ae229524",
            "modifiedTime": "2024-03-14T22:30:06.35"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "83263297-0ea8-4640-856a-ff7621b5a7ef",
        "fromTable": "Fact",
        "fromColumn": "Account ID",
        "toTable": "Account",
        "toColumn": "Account ID",
        "state": "ready",
        "modifiedTime": "2024-03-14T17:11:36.196667",
        "refreshedTime": "2024-03-14T17:11:36.196667"
      },
      {
        "name": "84787da3-95b1-457b-9959-ce35fd5e0c9e",
        "fromTable": "Fact",
        "fromColumn": "Opportunity ID",
        "toTable": "Opportunity",
        "toColumn": "Opportunity ID",
        "state": "ready",
        "modifiedTime": "2024-03-13T21:01:38.276667",
        "refreshedTime": "2024-03-13T21:01:38.276667"
      },
      {
        "name": "12e52b57-6662-46af-b5ac-22512b8920a2",
        "fromTable": "Fact",
        "fromColumn": "Sales Stage ID",
        "toTable": "Sales Stage",
        "toColumn": "Sales Stage ID",
        "state": "ready",
        "modifiedTime": "2024-03-13T21:01:38.293333",
        "refreshedTime": "2024-03-13T21:01:38.293333"
      },
      {
        "name": "1cc728c9-ecd5-4ce0-b6af-697dae236b73",
        "fromTable": "Fact",
        "fromColumn": "Partner ID",
        "toTable": "Partner",
        "toColumn": "Partner ID",
        "state": "ready",
        "modifiedTime": "2024-03-13T21:01:38.32",
        "refreshedTime": "2024-03-13T21:01:38.32"
      },
      {
        "name": "d9cd3f40-b159-4cc6-926e-bdad1ed0757d",
        "fromTable": "Fact",
        "fromColumn": "Product ID",
        "toTable": "Product",
        "toColumn": "Product ID",
        "state": "ready",
        "modifiedTime": "2024-03-13T21:01:38.276667",
        "refreshedTime": "2024-03-13T21:01:38.276667"
      },
      {
        "name": "98d80f3c-400e-4ae7-bace-1cd68a198593",
        "fromTable": "Fact",
        "fromColumn": "Estimated Close Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "state": "ready",
        "modifiedTime": "2024-03-14T00:37:39.4",
        "refreshedTime": "2024-03-14T00:37:39.4"
      },
      {
        "name": "93b6eeca-d989-42ab-b559-da6a1df3255a",
        "fromTable": "Fact",
        "fromColumn": "Create Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false,
        "state": "ready",
        "modifiedTime": "2024-03-14T00:37:39.396667",
        "refreshedTime": "2024-03-14T00:37:39.396667"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "modifiedTime": "2020-11-10T19:23:37.046667",
        "structureModifiedTime": "2024-03-13T22:10:57.583333",
        "linguisticMetadata": {}
      }
    ],
    "expressions": [
      {
        "name": "Fact A",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"nVxLi3THkf0rQ1PLBOX7oZ3BzELgmcUsjRceI2ZjZGMsw/x7xzvz5u3sui3Qp69a\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [EstimatedCloseDate = _t, #\"Opportunity ID\" = _t, #\"Sales Stage ID\" = _t, #\"Account ID\" = _t, #\"Partner ID\" = _t, #\"Product ID\" = _t, ProductRevenue = _t, FactoredProductRevenue = _t, #\"Create Date\" = _t, #\"Opportunity Days\" = _t, Year = _t, Month_Number = _t, Month = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"EstimatedCloseDate\", type datetime}, {\"Opportunity ID\", Int64.Type}, {\"Sales Stage ID\", Int64.Type}, {\"Account ID\", Int64.Type}, {\"Partner ID\", Int64.Type}, {\"Product ID\", Int64.Type}, {\"ProductRevenue\", Currency.Type}, {\"FactoredProductRevenue\", Currency.Type}, {\"Create Date\", Int64.Type}, {\"Opportunity Days\", Int64.Type}, {\"Year\", Int64.Type}, {\"Month_Number\", Int64.Type}, {\"Month\", type text}}),\n    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\", {\"EstimatedCloseDate\", Int64.Type}),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Year\", \"Month_Number\", \"Month\"}),\n    #\"Added to Column\" = Table.TransformColumns(#\"Removed Columns\", {{\"EstimatedCloseDate\", each _ + 2920, type number}}),\n    #\"Added to Column1\" = Table.TransformColumns(#\"Added to Column\", {{\"Create Date\", each _ + 2920, type number}}),\n    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added to Column1\",{{\"Create Date\", type date}, {\"EstimatedCloseDate\", type date}}),\n    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type2\",{\"FactoredProductRevenue\"}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns1\",{{\"EstimatedCloseDate\", \"Estimated Close Date\"}, {\"ProductRevenue\", \"Expected Revenue\"}, {\"Opportunity Days\", \"Opportunity Age\"}})\nin\n    #\"Renamed Columns\"",
        "queryGroup": "Base Data",
        "lineageTag": "2472069a-43f2-4ec2-a15f-f5e14d17730f",
        "modifiedTime": "2024-03-14T17:11:32.746667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      },
      {
        "name": "Fact B",
        "kind": "m",
        "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"nVzJriTZbf0VI5HLAOrOQ+8ECFo0YHuhZUMLSWh4Y8iC4RagvzfJQzKGzMiM0KKq\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [EstimatedCloseDate = _t, #\"Opportunity ID\" = _t, #\"Sales Stage ID\" = _t, #\"Account ID\" = _t, #\"Partner ID\" = _t, #\"Product ID\" = _t, ProductRevenue = _t, FactoredProductRevenue = _t, #\"Create Date\" = _t, #\"Opportunity Days\" = _t, Year = _t, Month_Number = _t, Month = _t]),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"EstimatedCloseDate\", type datetime}, {\"Opportunity ID\", Int64.Type}, {\"Sales Stage ID\", Int64.Type}, {\"Account ID\", Int64.Type}, {\"Partner ID\", Int64.Type}, {\"Product ID\", Int64.Type}, {\"ProductRevenue\", Currency.Type}, {\"FactoredProductRevenue\", Currency.Type}, {\"Create Date\", Int64.Type}, {\"Opportunity Days\", Int64.Type}, {\"Year\", Int64.Type}, {\"Month_Number\", Int64.Type}, {\"Month\", type text}}),\n    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"EstimatedCloseDate\", Int64.Type}}),\n    #\"Added to Column\" = Table.TransformColumns(#\"Changed Type1\", {{\"Create Date\", each _ + 2920, type number}}),\n    #\"Added to Column1\" = Table.TransformColumns(#\"Added to Column\", {{\"EstimatedCloseDate\", each _ + 2920, type number}}),\n    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added to Column1\",{{\"EstimatedCloseDate\", type date}, {\"Create Date\", type date}}),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type2\",{\"Year\", \"Month_Number\", \"Month\", \"FactoredProductRevenue\"}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"ProductRevenue\", \"Expected Revenue\"}, {\"EstimatedCloseDate\", \"Estimated Close Date\"}, {\"Opportunity Days\", \"Opportunity Age\"}})\nin\n    #\"Renamed Columns\"",
        "queryGroup": "Base Data",
        "lineageTag": "0d8bdfd0-e2c5-4f74-81a3-237e227916b1",
        "modifiedTime": "2024-03-14T17:11:32.746667",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Base Data",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      },
      {
        "folder": "Semantic Model",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1",
            "modifiedTime": "2024-03-13T20:57:24.456667"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Account\",\"Fact A\",\"Fact B\",\"Opportunity\",\"Partner\",\"Product\",\"Sales Stage\",\"Fact\",\"Calendar\",\"DAX Measures\"]",
        "modifiedTime": "2024-03-13T22:10:57.43"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1",
        "modifiedTime": "2020-11-10T19:28:21.996667"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.127.808.0 (24.03)",
        "modifiedTime": "2024-03-13T19:37:10.703333"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"CalcGroup\"]",
        "modifiedTime": "2024-03-13T22:02:53.73"
      },
      {
        "name": "__TEdtr",
        "value": "1",
        "modifiedTime": "2024-03-14T00:32:11.103333"
      }
    ]
  }
}